env: "local"
storage_path: "./storage/storage.db"
http_server:
  address: "127.0.0.1:8082"
  timeout: 4s # время на чтение запроса и отправку ответа
  idle_timeout: 60s # время жизни соединения с клиентом
  user: "myuser"
  password: "mypass"